#!/usr/bin/env python

import sys as _sys


def _load(filename: str) -> list[tuple[str, ...]]:
    with open(filename) as file:
        return [line.split() for line in file.read().splitlines()]


def solve1(filename: str) -> int:
    program = _load(filename)
    x = int(program[0][-1])
    return (x - 2) ** 2


def solve2(_) -> int:
    non_primes = 0
    lower = 106500
    upper = 106500 + 17000
    for candidate in range(lower, upper+1, 17):
        for factor in range(2, candidate):
            if candidate % factor == 0:
                non_primes += 1
                break
    return non_primes


def usage():
    print(f"usage: {_sys.argv[0]} 1|2 FILE")


def main():
    if len(_sys.argv) != 3:
        return usage()

    part = _sys.argv[1]
    filename = _sys.argv[2]

    if part == '1':
        print(solve1(filename))
    elif part == '2':
        print(solve2(filename))
    else:
        return usage()


if __name__ == '__main__':
    main()
