#!/usr/bin/env python

import sys as _sys


def _count_string_chars(s: str) -> int:
    i = s.find('"')
    if i == -1:
        return 0
    i += 1

    char_count = 0
    while i < len(s):
        if s[i] == '"':
            return char_count

        if s[i] == '\\':
            i += 1
            if s[i] in ['\\', '"']:
                pass
            elif s[i] == 'x':
                i += 2

        char_count += 1
        i += 1

    return char_count


def solve1(filename: str) -> int:
    total_overhead = 0
    with open(filename) as file:
        for line in file:
            raw_data = len(line.strip())
            string_data = _count_string_chars(line.strip())
            total_overhead += raw_data - string_data

    return total_overhead


def solve2(filename: str) -> int:
    total_size = 0
    with open(filename) as file:
        for line in file:
            raw_data = len(line.strip())
            encoded_size = raw_data + 2 + line.count('"') + line.count('\\')
            total_size += encoded_size - raw_data

    return total_size


def usage():
    print(f"usage: {_sys.argv[0]} 1|2 FILE")


def main():
    if len(_sys.argv) != 3:
        usage()
        return

    part = _sys.argv[1]
    filename = _sys.argv[2]

    if part == '1':
        print(solve1(filename))
    elif part == '2':
        print(solve2(filename))
    else:
        usage()


if __name__ == '__main__':
    main()
