#!/usr/bin/env python

import sys


directions: dict = {
    '<': (-1, 0),
    '>': (1, 0),
    '^': (0, 1),
    'v': (0, -1),
}


def _add(vec1: tuple, vec2: tuple) -> tuple:
    x1, x2 = vec1
    y1, y2 = vec2
    return (x1+y1, x2+y2)


def solve1(filename: str) -> int:
    pos = (0, 0)
    deliveries = {pos}
    with open(filename) as file:
        while True:
            char = file.read(1)
            if not char:
                break

            direction = directions.get(char)
            pos = _add(pos, direction)
            deliveries.add(pos)
    return len(deliveries)


def solve2(filename: str) -> int:
    pos1 = (0, 0)
    pos2 = (0, 0)
    deliveries = {pos1, pos2}
    with open(filename) as file:
        while True:
            char = file.read(2)
            if not char:
                break

            direction = directions.get(char[0])
            pos1 = _add(pos1, direction)
            deliveries.add(pos1)

            if len(char) == 2:
                direction = directions.get(char[1])
                pos2 = _add(pos2, direction)
                deliveries.add(pos2)
    return len(deliveries)


def usage():
    print(f"usage: {sys.argv[0]} 1|2 FILE")


def main():
    if len(sys.argv) != 3:
        return usage()

    part = sys.argv[1]
    filename = sys.argv[2]

    if part == '1':
        print(solve1(filename))
    elif part == '2':
        print(solve2(filename))
    else:
        return usage()


if __name__ == '__main__':
    main()
