#!/usr/bin/env python

import itertools as _it
import sys as _sys


def _sum_even_divisors(nums: list[int]) -> int:
    for n1, n2 in _it.combinations(nums, 2):
        if n1 % n2 == 0:
            return n1 // n2
        if n2 % n1 == 0:
            return n2 // n1


def solve1(filename: str) -> int:
    with open(filename) as file:
        rows = [[int(num) for num in line.split()] for line in file]
    return sum(max(row) - min(row) for row in rows)


def solve2(filename: str) -> int:
    with open(filename) as file:
        rows = [[int(num) for num in line.split()] for line in file]
    return sum(_sum_even_divisors(row) for row in rows)


def usage():
    print(f"usage: {_sys.argv[0]} 1|2 FILE")


def main():
    if len(_sys.argv) != 3:
        return usage()

    part = _sys.argv[1]
    filename = _sys.argv[2]

    if part == '1':
        print(solve1(filename))
    elif part == '2':
        print(solve2(filename))
    else:
        return usage()


if __name__ == '__main__':
    main()
