#!/usr/bin/env python

import re as _re
import sys as _sys


def _next_code(code: int) -> int:
    return (code * 252533) % 33554393


def _triangular_number(n: int) -> int:
    return sum(range(n+1))


def _to_index(row: int, column: int) -> int:
    n = row + column - 1
    return _triangular_number(n) - (row - 1)


def solve(filename: str) -> int:
    with open(filename) as file:
        text = file.read()
    row = int(_re.search(r'row (\d+)', text).groups()[0])
    column = int(_re.search(r'column (\d+)', text).groups()[0])
    iter_count = _to_index(row, column) - 1
    code = 20151125
    for _ in range(iter_count):
        code = _next_code(code)
    return code


def usage():
    print(f"usage: {_sys.argv[0]} 1|2 FILE")


def main():
    if len(_sys.argv) != 3:
        return usage()

    part = _sys.argv[1]
    filename = _sys.argv[2]

    if part == '1':
        print(solve(filename))
    elif part == '2':
        print("Snow begins to fall.")
    else:
        return usage()


if __name__ == '__main__':
    main()
