#!/usr/bin/env python

import hashlib
import sys


def solve(key: str, zeroes: int) -> int:
    n = 1
    prefix = '0' * zeroes
    while True:
        s = key + str(n)
        digest = hashlib.md5(s.encode('ascii')).hexdigest()
        if digest.startswith(prefix):
            return n
        else:
            n += 1


def usage():
    print(f"usage: {sys.argv[0]} 1|2 SECRET_KEY")


def main():
    if len(sys.argv) != 3:
        usage()
        return

    part = sys.argv[1]
    key = sys.argv[2]

    if part == '1':
        print(solve(key, 5))
    elif part == '2':
        print(solve(key, 6))
    else:
        usage()


if __name__ == '__main__':
    main()
