#!/usr/bin/env python

import collections as _c
import sys as _sys


def _letter_frequencies(lines: list[str]) -> list[_c.Counter]:
    counters = []
    for line in lines:
        word = line.strip()
        if len(word) > len(counters):
            for _ in range(len(counters), len(word)):
                counters.append(_c.Counter())

        for i, char in enumerate(word):
            counters[i].update(char)
    return counters


def solve1(filename: str) -> int:
    with open(filename) as file:
        letter_frequencies = _letter_frequencies(file.read().splitlines())
    return ''.join(counter.most_common()[0][0] for counter in letter_frequencies)


def solve2(filename: str) -> int:
    with open(filename) as file:
        letter_frequencies = _letter_frequencies(file.read().splitlines())
    return ''.join(counter.most_common()[-1][0] for counter in letter_frequencies)


def usage():
    print(f"usage: {_sys.argv[0]} 1|2 FILE")


def main():
    if len(_sys.argv) != 3:
        return usage()

    part = _sys.argv[1]
    filename = _sys.argv[2]

    if part == '1':
        print(solve1(filename))
    elif part == '2':
        print(solve2(filename))
    else:
        return usage()


if __name__ == '__main__':
    main()
