#!/usr/bin/env python

import sys as _sys


def solve1(filename: str) -> int:
    pos = depth = 0
    with open(filename) as file:
        for line in file:
            direction, amount = line.strip().split()
            if direction == 'forward':
                pos += int(amount)
            elif direction == 'down':
                depth += int(amount)
            elif direction == 'up':
                depth -= int(amount)
    return pos * depth


def solve2(filename: str) -> int:
    pos = depth = aim = 0
    with open(filename) as file:
        for line in file:
            direction, amount = line.strip().split()
            if direction == 'forward':
                pos += int(amount)
                depth += aim * int(amount)
            elif direction == 'down':
                aim += int(amount)
            elif direction == 'up':
                aim -= int(amount)
    return pos * depth


def usage():
    print(f"usage: {_sys.argv[0]} 1|2 FILE")


def main():
    if len(_sys.argv) != 3:
        return usage()

    part = _sys.argv[1]
    filename = _sys.argv[2]

    if part == '1':
        print(solve1(filename))
    elif part == '2':
        print(solve2(filename))
    else:
        return usage()


if __name__ == '__main__':
    main()
