#!/usr/bin/env python

import sys as _sys


def solve1(steps: int) -> int:
    xs = [0]
    i = 0
    max_val = 2017
    for val in range(1, max_val+1):
        i = (i + steps) % len(xs)
        xs.insert(i+1, val)
        i += 1
    return xs[(i+1) % len(xs)]


def solve2(steps: int) -> str:
    i_zero = 0
    after_zero = None
    i = 0
    max_val = int(5e7)
    for val in range(1, max_val+1):
        i = (i + steps) % val
        if i < i_zero:
            i_zero += 1
        elif i == i_zero:
            after_zero = val
        i += 1
    return after_zero


def usage():
    print(f"usage: {_sys.argv[0]} 1|2 STEPS")


def main():
    if len(_sys.argv) != 3:
        return usage()

    part = _sys.argv[1]
    steps = int(_sys.argv[2])

    if part == '1':
        print(solve1(steps))
    elif part == '2':
        print(solve2(steps))
    else:
        return usage()


if __name__ == '__main__':
    main()
