#!/usr/bin/env python

import sys as _sys
import typing as _t


def captcha(num: str, cmp: _t.Callable) -> int:
    digits = [
        int(num[i])
        for i in range(len(num))
        if num[i] == num[cmp(i, len(num))]
    ]
    return sum(digits)


def solve1(filename: str) -> int:
    with open(filename) as file:
        num = file.read().strip()
    return captcha(num, lambda i, n: (i+1) % n)


def solve2(filename: str) -> int:
    with open(filename) as file:
        num = file.read().strip()
    return captcha(num, lambda i, n: (i + n//2) % n)


def usage():
    print(f"usage: {_sys.argv[0]} 1|2 FILE")


def main():
    if len(_sys.argv) != 3:
        return usage()

    part = _sys.argv[1]
    filename = _sys.argv[2]

    if part == '1':
        print(solve1(filename))
    elif part == '2':
        print(solve2(filename))
    else:
        return usage()


if __name__ == '__main__':
    main()
