#!/usr/bin/env python

import sys


def solve1(filename: str) -> int:
    total = 0
    with open(filename) as file:
        for line in file:
            l, w, h = sorted([int(num) for num in line.split('x')])
            total += 2*l*w + 2*w*h + 2*h*l + l*w
    return total



def solve2(filename: str) -> int:
    total = 0
    with open(filename) as file:
        for line in file:
            l, w, h = sorted([int(num) for num in line.split('x')])
            total += 2*l + 2*w + l*w*h
    return total


def usage():
    print(f"usage: {sys.argv[0]} 1|2 FILE")


def main():
    if len(sys.argv) != 3:
        usage()
        return

    part = sys.argv[1]
    filename = sys.argv[2]

    if part == '1':
        print(solve1(filename))
    elif part == '2':
        print(solve2(filename))
    else:
        usage()


if __name__ == '__main__':
    main()
